version: "3.8"

services:
  backend:
    build: .
    container_name: auth_service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=auth_db
      - DB_PASS=secret
    volumes:
      - .:/app
      - /app/node_modules
      - keys_volume:/app/keys

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  keys_volume:
