version: '3.8'

services:
  react-app-mobx:
    image: react-app-mobx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  app-data:
